name: Terraform Azure Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-terraform@v2
        with:
          version: 1.1.7
      - run: terraform init
      - run: terraform plan
      - run: terraform apply